### PR TITLE
migrates to kotlin 1.5.x

### PR DESCRIPTION
**Pull request by OlegDokuka**

### CODE REVIEW

**Comment by OlegDokuka** [comment]
blocked by https://youtrack.jetbrains.com/issue/KTOR-2834

**Review by yschimke — APPROVED** [review]

**Comment by yschimke** [comment]
We seem hard blocked on this and getting out a release.  Can we land with this test disabled, so I can focus on getting a working build of rsocket-cli?

**Comment by clayly** [comment]
Can i somehow help with resolving this issue? Android development moved to kotlin 1.5.x

**Comment by altavir** [comment]
This one is a road blocker for https://github.com/mipt-npm/controls.kt. Is it possible to do a partial `dev` release, which do not cover native platforms?

**Pull request merged**
