### PR TITLE
Fix native coroutines dependency

### PR DESCRIPTION
**Pull request by whyoleg**
also minor: update gradle and remove todo.md

@yschimke can you check, that it works for you, without excluding kotlinx from rsocket-kotlin?
(build failed, so not published yet :( )

### CODE REVIEW

**Review by yschimke — APPROVED** [review]
I can check with either a PR snapshot, or land now and fix forward later.  And a big thanks from me.

**Comment by whyoleg** [comment]
Let's wait for build and snapshot publish, and then do real test. BTW, I can do it on my own, if needed (just need to setup `rsocket-cli` locally).

**Comment by yschimke** [comment]
> 
> 
> Let's wait for build and snapshot publish, and then do real test. BTW, I can do it on my own, if needed (just need to setup `rsocket-cli` locally).

There aren't many good unit tests but io.rsocket.RunMainKt should run straight out of the IDE.

**Comment by whyoleg** [comment]
Checked. Sync - ok, build - ok, run - ok.

**Comment by yschimke** [comment]
Will put up a PR - likely blocked on slow executor https://github.com/rsocket/rsocket-kotlin/runs/1263032155

**Comment by whyoleg** [comment]
I think It should be ok. Build on ubuntu is around 1h 20m because it build an test: jvm, js (legacy and IR) and native linux :)

**Pull request merged**
