### PR TITLE
Target 1.8

### PR DESCRIPTION
**Pull request by yschimke**
1.8 is LTS, really no point on 1.6 even for Android.

### CODE REVIEW

**Comment by whyoleg** [comment]
@yschimke What is the problem with 1.6?

**Comment by yschimke** [comment]
The way I'm using it, every difference causes additional breakages in the toolchain that I spend time working around.  Java 8 released in 2014 seems like a sensible baseline.  Are there clients on earlier versions you actively want to support?

**Comment by whyoleg** [comment]
Android isn't yet supported all java 8 features, and also it depends on Android API version, which features it support.
Also, I've rechecked ktor, coroutines, serialization, atomicfu, and no one of them use 1.8 target for core artifact, so I don't think, that  changing it here make sense.

**Comment by yschimke** [comment]
OK, It's just limiting in which features you can use in JVM modules.  e.g. no java.time.

If minimum supported is 1.6 then probably worth stating somewhere as it's not typical in Java OSS I'd say.  e.g. https://square.github.io/retrofit/ - "Retrofit requires at minimum Java 8+ or Android API 21+."

**Comment by whyoleg** [comment]
> OK, It's just limiting in which features you can use in JVM modules. e.g. no java.time.

But for now, we don't need any such features in `rsocket-kotlin` - so I don't see any issue. Even, almost all Kotlin code here is `common`.

> If minimum supported is 1.6 then probably worth stating somewhere as it's not typical in Java

May be, but do we really need to mention `minimal` requirements? The only thing, that we can mention, that it works on: Android (WS, TCP), JVM (WS, TCP), JS (WS), Native (TCP) (experimental soon)

**Comment by yschimke** [comment]
OK, I'll keep working around issues for now.  If I really get stuck I can drop back to rsocket-java, so not a blocker for me.

**Pull request closed without merging**
